Implement tentales-static
iZettle/tentales pull request #18
Opened 2018-03-29 16:49 UTC by dnjstrom

This is a middleware that simply wraps koa-static and which should be fairly straight forward to use in any project.

This is currently a stand-alone middleware that you have to manually include if needed. This might be fine if we believe most assets should be on a cdn anyway, or we might want to shoot for a more "batteries included" feel where the middleware is included by default.

*Note:*

I noticed that koa-static will automatically server the gzip or brotli versions if available and supported by the client, so I added compressed versions of hello.html for the lulz :D

2018-04-04 08:20 UTC, emiloberg requested changes
Nice! 

I'm wondering if we should include this in the package, but I can't come to a good conclusion right so lets move it there if needed.

2018-04-04 08:20 UTC, emiloberg commented on packages/tentales-example-simple/public/hello.html
> +</html>
Nit: Trailing line break

2018-04-04 08:20 UTC, emiloberg commented on packages/tentales-static/src/index.ts
> +// serveStatic.displayName = "Static"
Can we make this return something of type `Middleware` (which is annotated here https://github.com/iZettle/tentales/blob/1c77ba3cad9903b74756dc59aebad8f6651dc8b6/packages/tentales/src/index.d.ts#L80 )

2018-04-09 09:01 UTC, dnjstrom commented on packages/tentales-static/src/index.ts
> +// serveStatic.displayName = "Static"
Well, yeah. Isn't it though?

```typescript
export type StaticMiddleware = (props: StaticMiddlewareParams) => Middleware
```

2018-04-09 09:05 UTC, emiloberg commented on packages/tentales-static/src/index.ts
> +// serveStatic.displayName = "Static"
Nevermind me

2018-04-09 09:06 UTC, emiloberg approved these changes

2018-04-09 09:06 UTC, emiloberg approved these changes

2018-04-09 09:09 UTC, merged